# Generated by Django 6.0.5 on 2026-05-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_contactmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Date"),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Date"
                    ),
                ),
                (
                    "school",
                    models.CharField(max_length=254, verbose_name="School Name"),
                ),
                (
                    "department",
                    models.CharField(max_length=254, verbose_name="Department"),
                ),
                (
                    "date_range",
                    models.CharField(
                        help_text="e.g. Eki 2022 - Haz 2027 · Lisans Derecesi",
                        max_length=254,
                        verbose_name="Date Range",
                    ),
                ),
                (
                    "skills",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Python, Deep Learning",
                        max_length=254,
                        verbose_name="Skills",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Display Order")),
            ],
            options={
                "verbose_name": "Education",
                "verbose_name_plural": "Educations",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Date"),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Date"
                    ),
                ),
                ("title", models.CharField(max_length=254, verbose_name="Job Title")),
                ("company", models.CharField(max_length=254, verbose_name="Company")),
                (
                    "date_range",
                    models.CharField(
                        help_text="e.g. Ağu 2025 - Eyl 2025 · Ankara",
                        max_length=254,
                        verbose_name="Date Range",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "icon",
                    models.CharField(
                        default="icon-screen-desktop",
                        help_text="e.g. icon-screen-desktop, icon-screen-tablet",
                        max_length=100,
                        verbose_name="Icon Class",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Display Order")),
            ],
            options={
                "verbose_name": "Experience",
                "verbose_name_plural": "Experiences",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Date"),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Date"
                    ),
                ),
                ("name", models.CharField(max_length=254, verbose_name="Language")),
                (
                    "level",
                    models.CharField(
                        help_text="e.g. Ana dil, Professional Working Proficiency",
                        max_length=254,
                        verbose_name="Proficiency Level",
                    ),
                ),
                (
                    "is_highlighted",
                    models.BooleanField(
                        default=False,
                        help_text="Mavi arka planla vurgulanacak mı?",
                        verbose_name="Highlighted?",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="icon-speech",
                        help_text="e.g. icon-speech, icon-globe",
                        max_length=100,
                        verbose_name="Icon Class",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Display Order")),
            ],
            options={
                "verbose_name": "Language",
                "verbose_name_plural": "Languages",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Date"),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Date"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=254, verbose_name="Project Title"),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "github_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="GitHub URL"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="icon-trophy",
                        help_text="e.g. icon-trophy, icon-globe, icon-energy",
                        max_length=100,
                        verbose_name="Icon Class",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Display Order")),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Date"),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Date"
                    ),
                ),
                ("name", models.CharField(max_length=254, verbose_name="Skill Name")),
                (
                    "percentage",
                    models.IntegerField(
                        default=50,
                        help_text="0-100 arası bir değer girin",
                        verbose_name="Percentage",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Display Order")),
            ],
            options={
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
                "ordering": ("order",),
            },
        ),
    ]
